### ISSUE TITLE
Add logic for snake and ladder 

### ISSUE THREAD

**Issue by DipanshKhandelwal** [DipanshKhandelwal/Asobimasu#7]
Add logic and other working for snake and ladder game.

**Comment by shivamsaboo17** [comment]
@DipanshKhandelwal check out this simulation for S n L in Java. Feel free to make any changes.
https://gist.github.com/shivamsaboo17/9b3ac74d42f96477389d5f6269a1eabd

**Comment by Monal5031** [comment]
@shivamsaboo17 The implementation is pretty much like 2 players racing, you forgot to add the main logic for snake and ladder i.e. if the new rolled position coincides with a snake or ladder and the dice rolling part too 😛

**Comment by shivamsaboo17** [comment]
@Monal5031 did that now. I am also keeping count of snakes and ladders the player encounters. Feel free to add a map that can also keep track of indices but that won't help in gameplay though.
Also, the dice rolling would be the part of layout i.e if the user presses a button, then generate a random number. Also, the switching of players is part of GUI i.e when the user press button we can keep a modulo or something to rotate their turns.

**Comment by Monal5031** [comment]
Like in Tic Tac Toe we keep track of which button is being pressed incrementally and turn on/off (i.e. perform logic), likewise when the roll button will be pressed we'll be needing a logic to roll the dice too.
PS: I was asking for logic when a user steps on ladder i.e. we have to set the new position accordingly which is still not there, you added a count which is redundant.

**Comment by shivamsaboo17** [comment]
@Monal5031 done. Please check.

**Comment by shivamsaboo17** [comment]
@Monal5031 new position was already set before I made the counter update please check. I had updated player's position according to if the value is present in dictionary or not.

That was already done before man ... sigh.

check line 44. was already there before.

Even I thought the idea of adding count was hilarious but then I thought you wanted it for stats or something.

**Comment by Monal5031** [comment]
No I get it nice work 👍 , though the counting the ladder and snakes wouldn't be much of use.

**Comment by shivamsaboo17** [comment]
I know, haha, maybe we can find S/L ratio for about a million gamers and estimate the probability of a user getting bitten by the snake even before he plays the game.

**Comment by Monal5031** [comment]
Well, it sounds like some nice idea to me but we'll need to have test it
against the probablity of dice rolling.

**Comment by DipanshKhandelwal** [comment]
Nice work @shivamsaboo17 .
May be we can just display the encountered number of snakes and ladders at the   end of the game.

**Comment by DipanshKhandelwal** [comment]
@shivamsaboo17 , can you make the snakes and ladders that are generated to be different all the time?
This way it would be better as we will get a different board every time we play.

**Comment by shivamsaboo17** [comment]
Ok will do it soon
